task 10

diff --git a/processes_and_signals/10-process_and_pid_file b/processes_and_signals/10-process_and_pid_file
--- a/processes_and_signals/10-process_and_pid_file
+++ b/processes_and_signals/10-process_and_pid_file
@@ -1,5 +1,29 @@
 #!/usr/bin/env bash
-#i love you
-clean_up='rm /var/run/myscript.pid; exit $?'
+pid_file="/var/run/myscript.pid"
 
-echo $$ > "/var/run/myscript.pid"
+# Function to clean up and exit
+cleanup() {
+    echo "Deleting $pid_file and terminating the script."
+    rm -f "$pid_file"
+    exit
+}
+
+# Trap signals and call the cleanup function
+trap 'cleanup' SIGQUIT SIGTERM
+
+# Trap SIGTERM signal to display a message
+trap 'echo "I hate the kill command"' SIGTERM
+
+# Trap SIGINT signal to display a message
+trap 'echo "Y U no love me?!"' SIGINT
+
+# Create the PID file
+echo $$ > "$pid_file"
+echo "To infinity and beyond"
+
+# Infinite loop
+while true
+do
+    echo "To infinity and beyond"
+    sleep 1
+done
